'use client';

import jsPDF from 'jspdf';
import type { Shipment, Invoice, Quote } from './types';

// ============================================================
// FreightFlow professional PDF document generators.
// Modern, clean layout strictly based on user-provided templates:
//  - HAWB (House Air Waybill) — IATA Res 600a / Cargo-IMP FWB v16+ / Cargo-XML ONE Record
//  - HBL  (House Bill of Lading) — FIATA Multimodal Transport B/L (FBL), DCSA v3 eBL
//  - Commercial Invoice
//  - Freight Quotation
// ============================================================

const BRAND = [15, 76, 129] as [number, number, number];
const BRAND_DARK = [10, 55, 95] as [number, number, number];
const INK = [20, 28, 42] as [number, number, number];
const MUTED = [100, 110, 125] as [number, number, number];
const GRID = [190, 195, 205] as [number, number, number];
const BG_SOFT = [246, 248, 252] as [number, number, number];
const FIATA_GREEN = [0, 90, 70] as [number, number, number];
const MARGIN_L = 12;
const MARGIN_R = 12;
const PAGE_W = 210;
const W = PAGE_W - MARGIN_L - MARGIN_R;  // content width alias
const CONTENT_W = W;

// ---------- helpers ----------
type TxtOpts = { size?: number; bold?: boolean; italic?: boolean; color?: [number, number, number]; align?: 'left'|'right'|'center'; maxWidth?: number };
function text(doc: jsPDF, str: string, x: number, y: number, opts: TxtOpts = {}) {
  const { size = 9, bold = false, italic = false, color = INK, align = 'left', maxWidth } = opts;
  doc.setFont('helvetica', bold ? 'bold' : italic ? 'italic' : 'normal');
  doc.setFontSize(size);
  doc.setTextColor(color[0], color[1], color[2]);
  const s = str ?? '';
  if (maxWidth) {
    const lines = doc.splitTextToSize(s, maxWidth);
    doc.text(lines, x, y, { align, baseline: 'top' });
    return y + lines.length * (size * 0.42) + 1;
  }
  doc.text(s, x, y, { align, baseline: 'top' });
  return y + size * 0.42 + 1;
}
function line(doc: jsPDF, x1: number, y1: number, x2: number, y2: number, color: [number, number, number] = GRID, w = 0.2) {
  doc.setDrawColor(color[0], color[1], color[2]);
  doc.setLineWidth(w);
  doc.line(x1, y1, x2, y2);
}
function rect(doc: jsPDF, x: number, y: number, w: number, h: number, fill?: [number, number, number], stroke: [number, number, number] = GRID, sw = 0.2) {
  doc.setDrawColor(stroke[0], stroke[1], stroke[2]);
  doc.setLineWidth(sw);
  if (fill) {
    doc.setFillColor(fill[0], fill[1], fill[2]);
    doc.rect(x, y, w, h, 'FD');
  } else {
    doc.rect(x, y, w, h, 'S');
  }
}
function field(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value: string | number | undefined, opts: { labelSize?: number; valSize?: number; bold?: boolean; align?: 'left'|'center'|'right' } = {}) {
  rect(doc, x, y, w, h);
  doc.setFont('helvetica', 'bold').setFontSize(opts.labelSize ?? 6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(label.toUpperCase(), x + 1.5, y + 1.5, { baseline: 'top' });
  doc.setFont('helvetica', opts.bold ? 'bold' : 'normal').setFontSize(opts.valSize ?? 9).setTextColor(INK[0], INK[1], INK[2]);
  const v = value === undefined || value === null || value === '' ? '—' : String(value);
  const lines = doc.splitTextToSize(v, w - 3);
  doc.text(lines, x + 1.5, y + 4.8, { baseline: 'top', align: opts.align ?? 'left' });
}
function box(doc: jsPDF, x: number, y: number, w: number, h: number, title: string, body?: string) {
  rect(doc, x, y, w, h);
  doc.setFont('helvetica', 'bold').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(title.toUpperCase(), x + 1.5, y + 1.5, { baseline: 'top' });
  if (body) {
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
    const lines = doc.splitTextToSize(body, w - 3);
    doc.text(lines, x + 1.5, y + 5, { baseline: 'top' });
  }
}
function hline(doc: jsPDF, y: number) { line(doc, MARGIN_L, y, PAGE_W - MARGIN_R, y, GRID, 0.2); }
function fmtDate(d?: string) {
  if (!d) return '—';
  const dt = new Date(d);
  if (isNaN(dt.getTime())) return d;
  return dt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}
function fmtMoney(n: number, cur = 'USD') {
  try { return new Intl.NumberFormat('en-US', { style: 'currency', currency: cur, maximumFractionDigits: 2 }).format(n); } catch { return `${cur} ${n.toFixed(2)}`; }
}
function footer(doc: jsPDF, pageNum: number, total: number, color = BRAND) {
  const fy = 287;
  line(doc, MARGIN_L, fy - 2, PAGE_W - MARGIN_R, fy - 2, color, 0.3);
  doc.setFont('helvetica', 'italic').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('Generated by FreightFlow Logistics OS — computer-generated document, no signature required.', MARGIN_L, fy, { baseline: 'top' });
  doc.text(`Page ${pageNum} / ${total}`, PAGE_W - MARGIN_R, fy, { align: 'right', baseline: 'top' });
}

// ---------- modern section heading / helpers ----------
const SECTION_BG: [number, number, number] = [242, 246, 252];
function sectionH(doc: jsPDF, num: string, title: string, subtitle: string | undefined, y: number): number {
  const h = 7.5;
  doc.setFillColor(SECTION_BG[0], SECTION_BG[1], SECTION_BG[2]);
  doc.rect(MARGIN_L, y, CONTENT_W, h, 'F');
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(MARGIN_L, y, 10, h, 'F');
  doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(255, 255, 255);
  doc.text(num, MARGIN_L + 5, y + h / 2, { align: 'center', baseline: 'middle' });
  doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(BRAND_DARK[0], BRAND_DARK[1], BRAND_DARK[2]);
  doc.text(title.toUpperCase(), MARGIN_L + 13, y + h / 2, { baseline: 'middle' });
  if (subtitle) {
    doc.setFont('helvetica', 'normal').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
    doc.text(subtitle, PAGE_W - MARGIN_R, y + h / 2, { align: 'right', baseline: 'middle' });
  }
  return y + h + 2;
}
// pill(label, value) - inline pill row used in cargo/handling tables
function pill(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value: string, opts: { bold?: boolean; mono?: boolean } = {}) {
  rect(doc, x, y, w, h);
  doc.setFont('helvetica', 'bold').setFontSize(6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(label.toUpperCase(), x + 1.5, y + 1.3, { baseline: 'top' });
  doc.setFont('helvetica', opts.bold ? 'bold' : 'normal').setFontSize(9)
    .setTextColor(INK[0], INK[1], INK[2]);
  if (opts.mono) doc.setFont('courier', 'normal');
  const lines = doc.splitTextToSize(value || '—', w - 3);
  doc.text(lines, x + 1.5, y + 4.5, { baseline: 'top' });
}
// multiline field (for tall boxes)
function mfield(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value: string, opts: { bold?: boolean; mono?: boolean; align?: 'left'|'center'|'right' } = {}) {
  rect(doc, x, y, w, h);
  doc.setFont('helvetica', 'bold').setFontSize(6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(label.toUpperCase(), x + 1.5, y + 1.3, { baseline: 'top' });
  const v = (value && value.trim()) ? value : '—';
  doc.setFont(opts.mono ? 'courier' : 'helvetica', opts.bold ? 'bold' : 'normal')
    .setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
  const lines = doc.splitTextToSize(v, w - 3);
  doc.text(lines, x + 1.5, y + 4.5, { baseline: 'top', align: opts.align ?? 'left' });
}
// company identity block
const FORWARDER = {
  legalName: 'FreightFlow Logistics SARL',
  shortName: 'FreightFlow',
  address1: 'Lot II M 86 Bis, Antananarivo 101',
  address2: 'Analamanga, Madagascar',
  nif: 'NIF 200 123 456',
  iataCode: 'TNR-024-9',
  fiataMember: 'MG-FL-0017',
  phone: '+261 20 22 123 45',
  email: 'ops@freightflow.mg',
  city: 'Antananarivo',
};

// ============================================================
// HAWB (HOUSE AIR WAYBILL)
// Strictly based on HAWB_Template.md: IATA Res 600a / Cargo-IMP FWB v16+ / Cargo-XML ONE Record
// Modern & clean, brand-colored accent.
// ============================================================
function generateHAWB(s: Shipment): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = 10;

  // ===== HEADER =====
  // brand bar
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(0, 0, PAGE_W, 22, 'F');
  // accent stripe
  doc.setFillColor(255, 196, 0);
  doc.rect(0, 22, PAGE_W, 1.2, 'F');

  // left: forwarder ID
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(255, 255, 255);
  doc.text('ISSUED BY', MARGIN_L, 5, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(14).setTextColor(255, 255, 255);
  doc.text(FORWARDER.legalName.toUpperCase(), MARGIN_L, 8.5, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(7.5).setTextColor(220, 230, 245);
  doc.text(`${FORWARDER.address1}, ${FORWARDER.address2}`, MARGIN_L, 14.5, { baseline: 'top' });
  doc.text(`IATA Cargo Agent Code: ${FORWARDER.iataCode}  ·  ${FORWARDER.phone}  ·  ${FORWARDER.email}`, MARGIN_L, 17.5, { baseline: 'top' });

  // right: document type + HAWB #
  const hawbNum = s.mawbOrBl.startsWith('HAWB') || s.mawbOrBl.startsWith('AWB') ? s.mawbOrBl : `HAWB-${s.mawbOrBl}`;
  doc.setFont('helvetica', 'bold').setFontSize(7).setTextColor(220, 230, 245);
  doc.text('NON-NEGOTIABLE · HOUSE AIR WAYBILL', PAGE_W - MARGIN_R, 4, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(18).setTextColor(255, 255, 255);
  doc.text(hawbNum, PAGE_W - MARGIN_R, 7.5, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(7).setTextColor(220, 230, 245);
  doc.text(`Shipper's ref: ${s.reference}`, PAGE_W - MARGIN_R, 14, { align: 'right', baseline: 'top' });
  doc.text(`${s.direction.toUpperCase()} · ${s.incoterm} · ${s.currency}`, PAGE_W - MARGIN_R, 17, { align: 'right', baseline: 'top' });
  y = 28;

  // ===== SECTION 1 — PARTIES =====
  y = sectionH(doc, '1', 'Parties', 'Shipper · Consignee · Issuing Agent', y);
  const col3w = (CONTENT_W - 4) / 3;
  mfield(doc, MARGIN_L, y, col3w, 26, "Shipper's Name & Address",
    `${s.customerName}\n${s.doorPickupAddress || s.origin}\n${FORWARDER.city}, MG`);
  mfield(doc, MARGIN_L + col3w + 2, y, col3w, 26, "Consignee's Name & Address",
    `Consignee per booking\n${s.doorDeliveryAddress || s.destination}`);
  mfield(doc, MARGIN_L + 2*(col3w+2), y, col3w, 26, "Issuing Carrier's Agent",
    `${FORWARDER.legalName}\n${FORWARDER.city} (TNR), MG\nIATA: ${FORWARDER.iataCode}\nAccount: FF-${s.customerId.slice(-5)}`);
  y += 28;

  // ===== SECTION 2 — ROUTING =====
  y = sectionH(doc, '2', 'Routing', 'Departure · Carrier · Destination · Charges', y);
  const rY = y;
  const rH = 20;
  mfield(doc, MARGIN_L, y, col3w + 20, rH, 'Airport of Departure & Requested Routing', s.portOfLoading);
  mfield(doc, MARGIN_L + col3w + 22, y, col3w - 22, rH/2 - 1, 'To (1st)', s.portOfDischarge);
  mfield(doc, MARGIN_L + col3w + 22, y + rH/2, col3w - 22, rH/2, 'By First Carrier', s.carrier);
  mfield(doc, MARGIN_L + 2*col3w + 2, y, col3w - 2, rH, 'Airport of Destination', s.portOfDischarge);
  y += rH + 2;

  // Flight/currency/charges
  const sw = (CONTENT_W - 10) / 6;
  pill(doc, MARGIN_L + 0*(sw+2), y, sw, 13, 'Flight/Date', `${s.vesselOrFlight || '—'}  ${fmtDate(s.etd)}`);
  pill(doc, MARGIN_L + 1*(sw+2), y, sw, 13, 'Currency', s.currency);
  pill(doc, MARGIN_L + 2*(sw+2), y, sw, 13, 'CHGS Code', 'PP');
  pill(doc, MARGIN_L + 3*(sw+2), y, sw, 13, 'WT/VAL', 'PPD');
  pill(doc, MARGIN_L + 4*(sw+2), y, sw, 13, 'Other', 'PPD');
  pill(doc, MARGIN_L + 5*(sw+2), y, sw, 13, 'Declared Value', fmtMoney(s.totalAmount, s.currency), { bold: true });
  y += 15;

  // ===== SECTION 3 — MAWB CROSS-REFERENCE =====
  y = sectionH(doc, '3', 'MAWB Cross-Reference', 'Master AWB · Consolidation data', y);
  const masterAwb = s.masterRef || `195-${Math.floor(10000000 + Math.random()*89999999)}`;
  const consolPcs = Math.max(1, Math.floor(s.pieces * 1.4));
  pill(doc, MARGIN_L, y, 55, 12, 'Master AWB No.', masterAwb, { mono: true, bold: true });
  pill(doc, MARGIN_L + 57, y, 45, 12, 'Executed at (Place)', FORWARDER.city);
  pill(doc, MARGIN_L + 104, y, 38, 12, 'Date', fmtDate(new Date().toISOString()));
  pill(doc, MARGIN_L + 144, y, 42, 12, 'Pieces in Consol', String(consolPcs));
  y += 14;

  // ===== SECTION 4 — HANDLING INFORMATION =====
  y = sectionH(doc, '4', 'Handling Information', 'SHC · Security · Accounting', y);
  const handlingText =
    `HS Code: ${s.hsCode || '—'}  ·  ${s.hsDescription || ''}\n` +
    `Special Handling Codes: ${s.volume * s.weight > 3000 ? 'HEA, PER' : 'GEN'}\n` +
    `Security Status: SPX (cargo screened per IATA e-AWB SOP)\n` +
    `Accounting Info: Freight charges as per quote ${s.reference}  ·  ${s.notes || ''}`;
  mfield(doc, MARGIN_L, y, CONTENT_W, 28, 'Handling & Security', handlingText);
  y += 30;

  // ===== SECTION 5 — GOODS DESCRIPTION & CHARGES TABLE =====
  y = sectionH(doc, '5', 'Goods Description & Charges', 'Pieces · Weight · Rate · Nature of goods', y);
  const tblTop = y;
  // header
  const hdrH = 8;
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(MARGIN_L, y, CONTENT_W, hdrH, 'F');
  const gCols = [18, 28, 14, 18, 26, 30, 24, 0]; // pcs, grossWt, kg/lb, rateClass, chgWt, rateChg, total, nature (rest)
  let cx = MARGIN_L;
  const gLabels = ['Pcs (RCP)', 'Gross Wt', 'kg/lb', 'Rate Cl', 'Chg. Wt', 'Rate/Chg', 'Total', 'Nature & Qty of Goods (dim/vol)'];
  doc.setFont('helvetica', 'bold').setFontSize(6.5).setTextColor(255,255,255);
  const gColX: number[] = [];
  let cum = MARGIN_L;
  for (let i = 0; i < gLabels.length; i++) {
    gColX.push(cum);
    let ww: number;
    if (i === gLabels.length - 1) ww = MARGIN_L + CONTENT_W - cum;
    else { ww = gCols[i]; cum += ww; }
    doc.text(gLabels[i], cum + 1.5, y + hdrH/2, { baseline: 'middle' });
    if (i < gLabels.length - 1) {
      doc.setDrawColor(255,255,255).setLineWidth(0.15);
      doc.line(cum, y+1, cum, y+hdrH-1);
    }
  }
  y += hdrH;

  const chg = s.chargeableWeight ?? Math.max(s.weight, Math.round(s.volume * 1e6 / 6000));
  const ratePerKg = chg > 0 ? s.totalAmount / chg : 0;
  const wtCharge = Math.round(s.totalAmount * 0.85);
  const otherCharges = s.totalAmount - wtCharge;
  const dims = (s.dimLengthCm && s.dimWidthCm && s.dimHeightCm)
    ? `${s.dimLengthCm}×${s.dimWidthCm}×${s.dimHeightCm} cm × ${s.pieces}`
    : `Volumetric: 1:6000 · ${fmtNum(s.volume,3)} CBM`;
  const nature = `${s.commodity}\n${dims}\nCountry of origin: MG · HS ${s.hsCode || '—'}`;
  const nLines = doc.splitTextToSize(nature, gColX[gColX.length-1] - gColX[gColX.length-2] - 3);
  const bodyH = Math.max(18, nLines.length*4.2 + 4);

  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
  doc.text(String(s.pieces), gColX[0] + 1.5, y+3, { baseline: 'top' });
  doc.text(fmtNum(s.weight, 1), gColX[1] + 1.5, y+3, { baseline: 'top' });
  doc.text('K', gColX[2] + 1.5, y+3, { baseline: 'top' });
  doc.text('Q', gColX[3] + 1.5, y+3, { baseline: 'top' });
  doc.text(fmtNum(chg, 1), gColX[4] + 1.5, y+3, { baseline: 'top' });
  doc.text(ratePerKg.toFixed(2), gColX[5] + 1.5, y+3, { baseline: 'top' });
  doc.text(fmtMoney(wtCharge, s.currency), gColX[6] + 1.5, y+3, { baseline: 'top' });
  doc.text(nLines, gColX[7] + 1.5, y+3, { baseline: 'top' });

  // outline table
  rect(doc, MARGIN_L, tblTop, CONTENT_W, hdrH + bodyH);
  // vertical separators
  for (let i = 1; i < gLabels.length; i++) line(doc, gColX[i], tblTop, gColX[i], tblTop + hdrH + bodyH, GRID, 0.2);
  line(doc, MARGIN_L, y, MARGIN_L + CONTENT_W, y, GRID, 0.2); // header/body divider
  y += bodyH + 2;

  // Totals two-column (Prepaid / Collect)
  const tH = 7;
  const tW = CONTENT_W / 2 - 1;
  const totRow = (lbl: string, pval: string, cval: string, bold = false) => {
    mfield(doc, MARGIN_L, y, 55, tH, 'Prepaid: ' + lbl, pval, { bold });
    mfield(doc, MARGIN_L + 57, y, 50, tH, 'Collect: ' + lbl, cval || '—', { bold });
    y += tH + 0.5;
  };
  y += 1;
  totRow('Weight charge', fmtMoney(wtCharge, s.currency), '');
  totRow('Valuation charge', '—', '');
  totRow('Tax', '—', '');
  totRow('Other charges (agent)', fmtMoney(Math.round(otherCharges * 0.5), s.currency), '');
  totRow('Other charges (carrier)', fmtMoney(Math.round(otherCharges * 0.5), s.currency), '');
  mfield(doc, MARGIN_L, y, 55, tH, 'Total prepaid', fmtMoney(s.totalAmount, s.currency), { bold: true });
  mfield(doc, MARGIN_L + 57, y, 50, tH, 'Total collect', '—', { bold: true });
  y += tH + 3;

  // ===== SECTION 6 — CUSTOMS & DECLARED VALUE =====
  y = sectionH(doc, '6', 'Customs & Declared Value', 'DV Carriage · DV Customs · HS · Insurance', y);
  pill(doc, MARGIN_L, y, 42, 12, 'CC Conv. Rate', 'As per IATA TACT');
  pill(doc, MARGIN_L + 44, y, 42, 12, 'CC Dest. Charges', '—');
  pill(doc, MARGIN_L + 88, y, 36, 12, 'DV Carriage', fmtMoney(s.totalAmount, s.currency), { bold: true });
  pill(doc, MARGIN_L + 126, y, 30, 12, 'DV Customs', 'As per CI');
  pill(doc, MARGIN_L + 158, y, 28, 12, 'Insurance', 'NIL');
  y += 14;

  // ===== SECTION 7 — SHIPPER'S CERTIFICATION =====
  y = sectionH(doc, '7', "Shipper's Certification", 'Limitation-of-liability notice', y);
  const cert =
    "It is agreed that the goods described herein are accepted in apparent good order and condition (except as noted) for carriage SUBJECT TO THE CONDITIONS OF CONTRACT ON THE REVERSE HEREOF. ALL GOODS MAY BE CARRIED BY ANY OTHER MEANS INCLUDING ROAD OR ANY OTHER CARRIER UNLESS SPECIFIC CONTRARY INSTRUCTIONS ARE GIVEN HEREON BY THE SHIPPER, AND SHIPPER AGREES THAT THE SHIPMENT MAY BE CARRIED VIA INTERMEDIATE STOPPING PLACES WHICH THE CARRIER DEEMS APPROPRIATE. The shipper's attention is drawn to the notice concerning carrier's limitation of liability. Shipper may increase such limitation by declaring a higher value for carriage and paying a supplemental charge if required.";
  mfield(doc, MARGIN_L, y, CONTENT_W, 28, 'Certification', cert);
  y += 30;

  // ===== SECTION 8 — CARRIER'S / AGENT'S CERTIFICATION =====
  y = sectionH(doc, '8', "Carrier's / Issuing Agent's Certification", 'Execution', y);
  const sW = (CONTENT_W - 2) / 3;
  mfield(doc, MARGIN_L, y, sW, 18, 'Executed on (Date)', fmtDate(new Date().toISOString()));
  mfield(doc, MARGIN_L + sW + 1, y, sW, 18, 'At (Place)', `${FORWARDER.city}, Madagascar`);
  mfield(doc, MARGIN_L + 2*(sW+1), y, sW, 18, 'Signature of Issuing Carrier/Agent',
    `${FORWARDER.legalName}\nas agent for ${s.carrier}\n(authorized signatory — electronic)`);
  y += 20;

  // ===== DOCUMENT CONTROL FOOTER BLOCK =====
  y += 1;
  rect(doc, MARGIN_L, y, CONTENT_W, 12, BG_SOFT);
  doc.setFont('helvetica', 'bold').setFontSize(6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('DOCUMENT CONTROL', MARGIN_L + 2, y + 2, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(6.5);
  const ctrl = `Version: FWB v16+ / Cargo-XML (ONE Record) compatible  ·  IATA Res 672 e-AWB  ·  Originals: 3 (Carrier / Consignee / Shipper)  ·  Template ref: HAWB-FF-v1.0  ·  Generated by FreightFlow`;
  doc.text(ctrl, MARGIN_L + 2, y + 5.5, { baseline: 'top', maxWidth: CONTENT_W - 4 });

  footer(doc, 1, 1);
  return doc.output('blob');
}

// ============================================================
// HBL (HOUSE BILL OF LADING) — FIATA FBL / DCSA v3 eBL
// Strictly based on HBL_Template.md: FIATA Multimodal Transport B/L,
// UNCTAD/ICC Rules ICC Pub 481, DCSA transportDocument v3 field set.
// ============================================================
function generateHBL(s: Shipment): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const NAVY: [number, number, number] = [14, 42, 75];
  const GOLD: [number, number, number] = [198, 158, 68];
  const W = CONTENT_W;
  let y = 8;

  // ===== HEADER (FIATA navy/gold bar) =====
  doc.setFillColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.rect(0, 0, PAGE_W, 24, 'F');
  doc.setFillColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.rect(0, 24, PAGE_W, 1.2, 'F');

  doc.setFont('helvetica', 'bold').setFontSize(20).setTextColor(255, 255, 255);
  doc.text('FIATA', MARGIN_L, 4, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(7.5).setTextColor(215, 225, 245);
  doc.text('Fédération Internationale des Associations de Transitaires et Assimilés', MARGIN_L, 12, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(10).setTextColor(255, 255, 255);
  doc.text('MULTIMODAL TRANSPORT BILL OF LADING  (FBL)', MARGIN_L, 15.5, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(7).setTextColor(215, 225, 245);
  doc.text('Negotiable · Subject to UNCTAD/ICC Rules (ICC Publication 481) · DCSA B/L v3 eBL interoperable', MARGIN_L, 19.5, { baseline: 'top' });

  // negotiable + B/L number (right)
  const blNum = s.mawbOrBl.startsWith('HBL') || s.mawbOrBl.startsWith('BL') ? s.mawbOrBl : `HBL-${s.mawbOrBl}`;
  doc.setFont('helvetica', 'bold').setFontSize(13).setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.text('NEGOTIABLE  (TO ORDER)', PAGE_W - MARGIN_R, 4, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(16).setTextColor(255, 255, 255);
  doc.text(blNum, PAGE_W - MARGIN_R, 9.5, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(7).setTextColor(215, 225, 245);
  doc.text(`Booking ref: BOOK-${s.reference}`, PAGE_W - MARGIN_R, 15.5, { align: 'right', baseline: 'top' });
  doc.text(`Export refs: ${s.reference} · ${s.customerName}`, PAGE_W - MARGIN_R, 18.5, { align: 'right', baseline: 'top' });
  y = 30;

  // Reference row
  const refW = (W - 4) / 3;
  pill(doc, MARGIN_L, y, refW, 10, 'B/L No.', blNum, { mono: true, bold: true });
  pill(doc, MARGIN_L + refW + 2, y, refW, 10, 'Booking Ref. No.', `BOOK-${s.reference}`);
  pill(doc, MARGIN_L + 2*(refW+2), y, refW, 10, 'Export References', s.reference);
  y += 12;

  // ===== SECTION 1 — PARTIES =====
  y = sectionH(doc, '1', 'Parties', 'Shipper · Consignee · Notify · Forwarder · Carrier', y);
  const cw = (W - 3) / 4;
  mfield(doc, MARGIN_L + 0*(cw+1), y, cw, 26, 'Consignor / Shipper',
    `${s.customerName}\n${s.doorPickupAddress || s.origin}\nMadagascar`);
  mfield(doc, MARGIN_L + 1*(cw+1), y, cw, 26, 'Consigned to Order of / Consignee',
    `TO ORDER OF SHIPPER\n${s.doorDeliveryAddress || s.destination}`);
  mfield(doc, MARGIN_L + 2*(cw+1), y, cw, 26, 'Notify Address',
    `Notify party per booking\n${s.doorDeliveryAddress || s.destination}`);
  mfield(doc, MARGIN_L + 3*(cw+1), y, cw, 26, 'Freight Forwarder / Issuing MTO',
    `${FORWARDER.legalName}\nFIATA Member ID: ${FORWARDER.fiataMember}\nas Multimodal Transport Operator`);
  y += 28;

  // carrier row
  mfield(doc, MARGIN_L, y, W, 11, 'Carrier (actual, if subcontracted)', `${s.carrier}  ·  ${s.vesselOrFlight || 'Ocean vessel per booking'}`);
  y += 13;

  // ===== SECTION 2 — ROUTING =====
  y = sectionH(doc, '2', 'Routing', 'Place of receipt → POL → Vessel → POD → Delivery', y);
  const rw = (W - 5) / 6;
  const rh = 16;
  mfield(doc, MARGIN_L + 0*(rw+1), y, rw, rh, 'Place of Receipt', s.origin);
  mfield(doc, MARGIN_L + 1*(rw+1), y, rw, rh, 'Port of Loading', s.portOfLoading);
  mfield(doc, MARGIN_L + 2*(rw+1), y, rw*2 + 1, rh, 'Ocean Vessel / Voyage No.', s.vesselOrFlight || 'TBN');
  mfield(doc, MARGIN_L + 4*(rw+1), y, rw, rh, 'Port of Discharge', s.portOfDischarge);
  mfield(doc, MARGIN_L + 5*(rw+1), y, rw, rh, 'Place of Delivery', s.destination);
  y += rh + 2;
  mfield(doc, MARGIN_L, y, W, 10, 'Final Destination (if on-carriage)', s.doorDeliveryAddress || s.destination);
  y += 12;

  // ===== SECTION 3 — MBL CROSS-REFERENCE =====
  y = sectionH(doc, '3', 'MBL Cross-Reference', 'Master B/L · Carrier booking · Container/Seal', y);
  const mbl = s.masterRef || `MAEU${Math.floor(100000000 + Math.random()*899999999)}`;
  const containerType = s.volume >= 60 ? '40HC' : s.volume >= 28 ? '40GP' : s.volume >= 14 ? '20GP' : 'LCL';
  const containerNo = containerType === 'LCL' ? 'LCL (consolidated)' : `${containerType === '20GP' ? 'MSKU' : 'TCNU'}${Math.floor(1000000 + Math.random()*8999999)}`;
  const sealNo = containerType === 'LCL' ? 'CFS seal per CFS station' : `MG-TMM-${Math.floor(10000 + Math.random()*89999)}`;
  pill(doc, MARGIN_L, y, 55, 12, 'Master B/L No.', mbl, { mono: true, bold: true });
  pill(doc, MARGIN_L + 57, y, 55, 12, 'Carrier Booking Ref.', `BOOK-${s.reference}`);
  pill(doc, MARGIN_L + 114, y, 72, 12, 'Container / Seal No.', `${containerNo}  ·  Seal ${sealNo}`, { mono: true });
  y += 14;

  // ===== SECTION 4 — CARGO DETAILS =====
  y = sectionH(doc, '4', 'Cargo Details', 'Marks · Packages · Description · Weight · Measurement', y);
  const cargoTop = y;
  const cHdr = 8;
  doc.setFillColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.rect(MARGIN_L, y, W, cHdr, 'F');
  const cargoColW = [30, 38, 0, 30, 28]; // marks, pkgs, desc(rest), grossWt, meas
  const cLabels = ['Marks & Numbers', 'No. & Kind of Packages', 'Description of Goods', 'Gross Weight (kg)', 'Measurement (CBM)'];
  const cx: number[] = [];
  let cumC = MARGIN_L;
  for (let i = 0; i < cLabels.length; i++) {
    cx.push(cumC);
    let ww: number;
    if (i === 2) ww = MARGIN_L + W - cumC - cargoColW[3] - cargoColW[4];
    else { ww = cargoColW[i]; cumC += ww; }
    if (i === 3) cumC = MARGIN_L + W - cargoColW[4];
    if (i === 4) cumC = MARGIN_L + W;
    doc.setFont('helvetica', 'bold').setFontSize(6.5).setTextColor(255,255,255);
    doc.text(cLabels[i], cx[i] + 1.5, y + cHdr/2, { baseline: 'middle' });
    if (i < cLabels.length - 1) {
      doc.setDrawColor(255,255,255).setLineWidth(0.15);
      doc.line(cx[i] + ww, y+1, cx[i] + ww, y+cHdr-1);
    }
  }
  y += cHdr;

  const marks = `${blNum}\nC/NOS: 1–${s.pieces}\nORIGIN: MG`;
  const marksL = doc.splitTextToSize(marks, cx[1]-cx[0]-3);
  const pkgsStr = `${s.pieces} ${s.pieces === 1 ? 'PACKAGE' : 'PACKAGES'}\n${containerType}\n${s.commodity.slice(0, 24)}`;
  const pkgsL = doc.splitTextToSize(pkgsStr, cx[2]-cx[1]-3);
  const descBody =
    `${s.commodity}\nHS Code: ${s.hsCode || '—'}  ·  ${s.hsDescription || ''}\n` +
    `Container type: ${containerType}  ·  Container No: ${containerNo}\n` +
    `Seal No: ${sealNo}\n` +
    `Shipper's declared weight/count — SLAC / SHIPPER'S LOAD, STOW & COUNT`;
  const descL = doc.splitTextToSize(descBody, cx[3]-cx[2]-3);
  const cargoBodyH = Math.max(28, Math.max(marksL.length, pkgsL.length, descL.length)*4 + 5);

  doc.setFont('helvetica', 'normal').setFontSize(8.5).setTextColor(INK[0], INK[1], INK[2]);
  doc.text(marksL, cx[0]+1.5, y+2.5, { baseline: 'top' });
  doc.setFont('helvetica', 'bold');
  doc.text(pkgsL, cx[1]+1.5, y+2.5, { baseline: 'top' });
  doc.setFont('helvetica', 'normal');
  doc.text(descL, cx[2]+1.5, y+2.5, { baseline: 'top' });
  doc.text(fmtNum(s.weight, 1), cx[3]+1.5, y+2.5, { baseline: 'top' });
  doc.text(fmtNum(s.volume, 3), cx[4]+1.5, y+2.5, { baseline: 'top' });

  rect(doc, MARGIN_L, cargoTop, W, cHdr + cargoBodyH);
  for (let i = 1; i < cLabels.length; i++) {
    const vx = i === 3 ? MARGIN_L + W - cargoColW[3] - cargoColW[4] : i === 4 ? MARGIN_L + W - cargoColW[4] : cx[i];
    line(doc, vx, cargoTop, vx, cargoTop + cHdr + cargoBodyH, GRID, 0.2);
  }
  line(doc, MARGIN_L, y, MARGIN_L+W, y, GRID, 0.2);
  y += cargoBodyH + 2;

  // ===== SECTION 5 — FREIGHT & CHARGES =====
  y = sectionH(doc, '5', 'Freight & Charges', 'Prepaid/Collect · Originals · Issue · Declared value', y);
  const fw = (W - 3) / 4;
  const fh = 18;
  mfield(doc, MARGIN_L + 0*(fw+1), y, fw, fh, 'Freight Payable at', `${FORWARDER.city}, MG`);
  mfield(doc, MARGIN_L + 1*(fw+1), y, fw, fh, 'Freight', `☒ Prepaid    ☐ Collect\n\n${s.incoterm} · ${s.direction.toUpperCase()}`);
  mfield(doc, MARGIN_L + 2*(fw+1), y, fw, fh, 'No. of Original B/Ls', 'THREE (3/3)');
  mfield(doc, MARGIN_L + 3*(fw+1), y, fw, fh, 'Declared Value (ad valorem)', fmtMoney(s.totalAmount, s.currency), { bold: true });
  y += fh + 2;
  mfield(doc, MARGIN_L, y, W/2 + 0.5, fh, 'Place and Date of Issue',
    `${FORWARDER.city}, Madagascar · ${fmtDate(new Date().toISOString())}\nETD ${fmtDate(s.etd)} · ETA ${fmtDate(s.eta)}`);
  mfield(doc, MARGIN_L + W/2 + 1.5, y, W/2 - 1.5, fh, 'On-board Notation',
    '☒ Shipped on Board   ☐ Received for Shipment\nDated: ' + fmtDate(s.etd));
  y += fh + 2;

  // ===== SECTION 6 — ON-BOARD / RECEIVED NOTATION =====
  y = sectionH(doc, '6', 'On-Board / Received-for-Shipment Notation', 'Contract clause', y);
  const notation =
    'Taken in charge in apparent good order and condition, unless otherwise noted herein, at the place of receipt for transport and delivery to the consignee as mentioned above. ONE (1) of these Multimodal Transport Bills of Lading must be surrendered duly endorsed in exchange for the goods. In witness whereof the original Multimodal Transport Bills of Lading, all of this tenor and date, have been signed in the number stated above, one of which being accomplished, the other(s) to be void.';
  mfield(doc, MARGIN_L, y, W, 22, 'Notation', notation);
  y += 24;

  // ===== SECTION 7 — FIATA STANDARD CONDITIONS =====
  y = sectionH(doc, '7', 'FIATA Standard Conditions (1997) — Governing Terms', 'Summary (full conditions overleaf)', y);
  rect(doc, MARGIN_L, y, W, 26, [250,250,252], GRID);
  doc.setFont('helvetica', 'bold').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  const terms = [
    ['Cl. 1', 'Applicability / scope of MTO liability'],
    ['Cl. 2', 'Liability for acts/omissions of servants, agents, subcontractors'],
    ['Cl. 3', 'Negotiability — this FBL constitutes title; holder by endorsement entitled to goods'],
    ['Cl. 4', 'Dangerous goods — burden of proof on Merchant re hazard knowledge'],
    ['Cl. 6.2/7/8', 'Declared value / ad valorem rate provisions'],
  ];
  const colTw = W / 5;
  terms.forEach((t, i) => {
    doc.text(t[0], MARGIN_L + i*colTw + 2, y+2.5, { baseline: 'top' });
    doc.setFont('helvetica', 'normal');
    const tlines = doc.splitTextToSize(t[1], colTw - 4);
    doc.text(tlines, MARGIN_L + i*colTw + 2, y+6, { baseline: 'top' });
    doc.setFont('helvetica', 'bold');
  });
  doc.setFont('helvetica', 'normal').setFontSize(6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('Full Standard Conditions printed overleaf / incorporated by reference.  Validity per FIATA Standards: 5 years from issue.', MARGIN_L+2, y+21, { baseline: 'top' });
  y += 28;

  // ===== SECTION 8 — SIGNATURE =====
  y = sectionH(doc, '8', 'Signature', 'Signed for the Freight Forwarder / MTO', y);
  const sw8 = (W - 2) / 3;
  mfield(doc, MARGIN_L, y, sw8, 20, 'Signature', '____________________________');
  mfield(doc, MARGIN_L + sw8 + 1, y, sw8, 20, 'Name / Title', `Authorized Signatory\nOperations Manager\n${FORWARDER.legalName}`);
  mfield(doc, MARGIN_L + 2*(sw8+1), y, sw8, 20, 'Place / Date',
    `${FORWARDER.city}, Madagascar\n${fmtDate(new Date().toISOString())}\nas agent for the carrier ${s.carrier}`);
  y += 22;

  // ===== DOCUMENT CONTROL =====
  rect(doc, MARGIN_L, y, W, 12, BG_SOFT);
  doc.setFont('helvetica', 'bold').setFontSize(6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('DOCUMENT CONTROL', MARGIN_L + 2, y+2, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(6.5);
  const ctrl2 = 'Standard: FIATA FBL (paper) · Data model: UN/CEFACT MMT-aligned eFBL · Interoperability: DCSA Bill of Lading v3 (transportDocument JSON) · Verification: electronic signature · Template ref: HBL-FF-v1.0 · Generated by FreightFlow';
  doc.text(ctrl2, MARGIN_L + 2, y + 5.5, { baseline: 'top', maxWidth: W-4 });

  footer(doc, 1, 1, NAVY);
  return doc.output('blob');
}

// ============================================================
// Dispatcher — picks HAWB or HBL depending on mode
// ============================================================
export function generateShipmentBL(s: Shipment): Blob {
  return s.mode === 'air' ? generateHAWB(s) : generateHBL(s);
}
function generateFIATABL(s: Shipment): Blob { return generateHBL(s); } // backward-compat alias

// ============================================================
// COMMERCIAL INVOICE — clean, professional
// ============================================================
export function generateInvoicePDF(inv: Invoice): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = 12;
  // brand header
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(0, 0, PAGE_W, 18, 'F');
  doc.setFont('helvetica', 'bold').setFontSize(18).setTextColor(255, 255, 255);
  doc.text('FREIGHTFLOW', MARGIN_L, 6, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(255, 255, 255);
  doc.text('FreightFlow Logistics SARL · Antananarivo, Madagascar · ops@freightflow.mg', MARGIN_L, 12.5, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(16).setTextColor(255, 255, 255);
  doc.text('INVOICE', PAGE_W - MARGIN_R, 5, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(9);
  doc.text(`No. ${inv.number}`, PAGE_W - MARGIN_R, 11, { align: 'right', baseline: 'top' });
  y = 24;

  // Bill-to / invoice meta boxes
  const bw = (W - 4) / 3;
  field(doc, MARGIN_L, y, bw, 24, 'BILL TO', inv.customerName);
  field(doc, MARGIN_L + bw + 2, y, bw, 24, 'INVOICE DETAILS',
    `Issue date: ${fmtDate(inv.issueDate)}\nDue date:   ${fmtDate(inv.dueDate)}\nStatus:     ${inv.status.toUpperCase()}\nCurrency:   ${inv.currency}`);
  field(doc, MARGIN_L + 2 * (bw + 2), y, bw, 24, 'PAYMENT',
    `Bank: BNI Madagascar\nSWIFT: BNIMMGAA\nIBAN: MG46 0000 5000 0100 1234 5678 90\nTerms: Net ${Math.max(0, Math.ceil((new Date(inv.dueDate).getTime() - new Date(inv.issueDate).getTime()) / 86400000))} days`);
  y += 28;

  // Items table
  const tblTop = y;
  const colW = [85, 28, 25, 28];  // desc, qty, rate, amount
  const colStarts = [MARGIN_L, MARGIN_L + colW[0], MARGIN_L + colW[0] + colW[1], MARGIN_L + colW[0] + colW[1] + colW[2]];
  rect(doc, MARGIN_L, y, W, 7, BG_SOFT);
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('DESCRIPTION', colStarts[0] + 2, y + 2, { baseline: 'top' });
  doc.text('QTY', colStarts[1] + colW[1] - 2, y + 2, { align: 'right', baseline: 'top' });
  doc.text('RATE', colStarts[2] + colW[2] - 2, y + 2, { align: 'right', baseline: 'top' });
  doc.text('AMOUNT', colStarts[3] + colW[3] - 2, y + 2, { align: 'right', baseline: 'top' });
  y += 7;

  let subtotal = 0;
  inv.items.forEach((it, idx) => {
    const isLast = idx === inv.items.length - 1;
    const lines = doc.splitTextToSize(it.description, colW[0] - 4);
    const rh = Math.max(7, lines.length * 4 + 2);
    if (idx % 2 === 1) doc.setFillColor(250, 251, 253).rect(MARGIN_L, y, W, rh, 'F');
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
    doc.text(lines, colStarts[0] + 2, y + 1.5, { baseline: 'top' });
    doc.text('1', colStarts[1] + colW[1] - 2, y + 2, { align: 'right', baseline: 'top' });
    doc.text(fmtMoney(it.amount, inv.currency), colStarts[2] + colW[2] - 2, y + 2, { align: 'right', baseline: 'top' });
    doc.text(fmtMoney(it.amount, inv.currency), colStarts[3] + colW[3] - 2, y + 2, { align: 'right', baseline: 'top' });
    subtotal += it.amount;
    y += rh;
    if (!isLast) line(doc, MARGIN_L, y, MARGIN_L + W, y, GRID, 0.15);
  });
  rect(doc, MARGIN_L, tblTop, W, y - tblTop);  // outer border
  for (let i = 1; i < colStarts.length; i++) line(doc, colStarts[i], tblTop, colStarts[i], y);
  y += 2;

  // totals (right aligned)
  const totX = MARGIN_L + W - 60;
  const totW = 60;
  const tot = (label: string, value: string, bold = false, fill = false) => {
    const h = 7;
    if (fill) { doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]); doc.rect(totX, y, totW, h, 'F'); }
    doc.setFont('helvetica', bold ? 'bold' : 'normal').setFontSize(bold ? 11 : 9).setTextColor(fill ? 255 : INK[0], fill ? 255 : INK[1], fill ? 255 : INK[2]);
    doc.text(label, totX + 3, y + 2, { baseline: 'top' });
    doc.text(value, totX + totW - 3, y + 2, { align: 'right', baseline: 'top' });
    y += h;
  };
  tot('Subtotal', fmtMoney(inv.subtotal, inv.currency));
  tot('VAT / Tax (0%)', fmtMoney(inv.tax, inv.currency));
  tot('TOTAL DUE', fmtMoney(inv.total, inv.currency), true, true);
  y += 4;

  // Status stamp / paid
  if (inv.status === 'paid') {
    doc.setDrawColor(20, 140, 70).setLineWidth(0.8).setTextColor(20, 140, 70);
    doc.setFont('helvetica', 'bold').setFontSize(14);
    doc.roundedRect(totX, y + 2, totW, 10, 2, 2, 'S');
    doc.text('PAID', totX + totW / 2, y + 5, { align: 'center', baseline: 'top' });
    doc.setTextColor(INK[0], INK[1], INK[2]);
    y += 14;
  } else if (inv.status === 'overdue') {
    doc.setDrawColor(180, 40, 40).setLineWidth(0.8).setTextColor(180, 40, 40);
    doc.setFont('helvetica', 'bold').setFontSize(14);
    doc.roundedRect(totX, y + 2, totW, 10, 2, 2, 'S');
    doc.text('OVERDUE', totX + totW / 2, y + 5, { align: 'center', baseline: 'top' });
    doc.setTextColor(INK[0], INK[1], INK[2]);
    y += 14;
  } else {
    y += 4;
  }

  // OOBO / e-invoice block
  if (inv.einvoice) {
    rect(doc, MARGIN_L, y, W, 16, [235, 250, 240], [80, 160, 110], 0.5);
    doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(20, 90, 50);
    doc.text('OOBO / DGI E-INVOICE (MADAGASCAR)', MARGIN_L + 3, y + 2, { baseline: 'top' });
    doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(20, 90, 50);
    doc.text(`UID: ${inv.einvoice.ooboUid ?? 'pending'}  ·  NIF Emitter: ${inv.einvoice.nifEmitter}  ·  HTVA: ${fmtMoney(inv.einvoice.htva, inv.currency)}  ·  VAT (${(inv.einvoice.tvaRate * 100).toFixed(0)}%): ${fmtMoney(inv.einvoice.tva, inv.currency)}  ·  TTC: ${fmtMoney(inv.einvoice.ttc, inv.currency)}  ·  Payment: ${inv.einvoice.paymentMethod.toUpperCase()}`, MARGIN_L + 3, y + 8, { baseline: 'top' });
    y += 18;
  }

  // thank-you
  doc.setFont('helvetica', 'italic').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('Thank you for your business. 🇲🇬 Payment is due per agreed terms; bank details above.', MARGIN_L, y + 4, { baseline: 'top' });

  footer(doc, 1, 1);
  return doc.output('blob');
}

// ============================================================
// QUOTATION
// ============================================================
export function generateQuotePDF(q: Quote): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = 12;
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(0, 0, PAGE_W, 18, 'F');
  doc.setFont('helvetica', 'bold').setFontSize(18).setTextColor(255, 255, 255);
  doc.text('FREIGHTFLOW', MARGIN_L, 6, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(255, 255, 255);
  doc.text('FreightFlow Logistics SARL · Antananarivo, Madagascar · quotes@freightflow.mg', MARGIN_L, 12.5, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(16).setTextColor(255, 255, 255);
  doc.text('FREIGHT QUOTATION', PAGE_W - MARGIN_R, 5, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(9);
  doc.text(`No. ${q.number}`, PAGE_W - MARGIN_R, 11, { align: 'right', baseline: 'top' });
  doc.text(`Valid until: ${fmtDate(q.validUntil)}`, PAGE_W - MARGIN_R, 14, { align: 'right', baseline: 'top' });
  y = 24;

  // Customer & routing block
  const bw = (W - 2) / 2;
  field(doc, MARGIN_L, y, bw, 22, 'PREPARED FOR',
    `${q.customerName}\n${q.customerEmail ?? ''}`);
  field(doc, MARGIN_L + bw + 2, y, bw, 22, 'ROUTING',
    `${q.mode.toUpperCase()} ${q.direction.toUpperCase()}\n${q.origin}  →  ${q.destination}\nCommodity: ${q.commodity} · ${fmtNum(q.weight, 1)} kg · ${fmtNum(q.volume, 3)} CBM`);
  y += 26;

  // Items
  rect(doc, MARGIN_L, y, W, 7, BG_SOFT);
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('CHARGE ITEM', MARGIN_L + 3, y + 2, { baseline: 'top' });
  doc.text('AMOUNT (USD)', MARGIN_L + W - 3, y + 2, { align: 'right', baseline: 'top' });
  y += 7;
  const items: [string, number][] = [
    ['Freight charges (ocean/air)', q.freightRate],
    ['Customs processing & documentation', q.customsFee],
    ['Inland trucking & delivery', q.truckingFee],
  ];
  items.forEach(([lbl, amt], i) => {
    const rh = 7;
    if (i % 2 === 1) doc.setFillColor(250, 251, 253).rect(MARGIN_L, y, W, rh, 'F');
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
    doc.text(lbl, MARGIN_L + 3, y + 2, { baseline: 'top' });
    doc.text(fmtMoney(amt, 'USD'), MARGIN_L + W - 3, y + 2, { align: 'right', baseline: 'top' });
    y += rh;
  });
  line(doc, MARGIN_L, y, MARGIN_L + W, y);
  y += 1;
  doc.setFont('helvetica', 'bold').setFontSize(12).setTextColor(BRAND_DARK[0], BRAND_DARK[1], BRAND_DARK[2]);
  doc.text('ALL-IN TOTAL', MARGIN_L + 3, y + 2, { baseline: 'top' });
  doc.text(fmtMoney(q.total, 'USD'), MARGIN_L + W - 3, y + 2, { align: 'right', baseline: 'top' });
  y += 10;

  // T&Cs
  rect(doc, MARGIN_L, y, W, 42, [250, 250, 252], GRID);
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('TERMS & CONDITIONS', MARGIN_L + 3, y + 2, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  const tc = [
    '• Rates valid until date shown above, subject to carrier space, equipment availability and bunker/security surcharges.',
    '• Quoted amounts exclude insurance, duties, taxes (VAT/TVA), demurrage, detention and storage beyond free time (7 days at CFS).',
    '• Transit times are estimates; FreightFlow is not liable for carrier schedule changes, customs inspection delays or force majeure.',
    '• Dangerous goods / perishables require prior written approval and may incur additional handling fees.',
    '• Payment terms: 50% deposit on booking confirmation; balance due prior to document / cargo release.',
    '• Quotation may be accepted by signed return, email confirmation or by tendering cargo against this reference.',
  ].join('\n');
  doc.text(doc.splitTextToSize(tc, W - 6), MARGIN_L + 3, y + 6, { baseline: 'top' });

  footer(doc, 1, 1);
  return doc.output('blob');
}

// ============================================================
// Download helper
// ============================================================
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// format number helper for docs
function fmtNum(n: number, d: number) {
  return new Intl.NumberFormat('en-US', { minimumFractionDigits: n % 1 ? d : 0, maximumFractionDigits: d }).format(n);
}
