'use client';

import jsPDF from 'jspdf';
import type { Shipment, Invoice, Quote } from './types';

// ============================================================
// FreightFlow professional PDF document generators.
// - Air Waybill (AWB): IATA-style layout
// - FIATA Multimodal Transport Bill of Lading (FBL) — official FIATA layout
// - Commercial Invoice
// - Freight Quotation
// ============================================================

const BRAND = [15, 76, 129] as [number, number, number];
const BRAND_DARK = [10, 55, 95] as [number, number, number];
const INK = [20, 28, 42] as [number, number, number];
const MUTED = [100, 110, 125] as [number, number, number];
const GRID = [190, 195, 205] as [number, number, number];
const BG_SOFT = [246, 248, 252] as [number, number, number];
const FIATA_GREEN = [0, 90, 70] as [number, number, number];
const MARGIN_L = 12;
const MARGIN_R = 12;
const PAGE_W = 210;
const W = PAGE_W - MARGIN_L - MARGIN_R;  // content width alias
const CONTENT_W = W;

// ---------- helpers ----------
type TxtOpts = { size?: number; bold?: boolean; italic?: boolean; color?: [number, number, number]; align?: 'left'|'right'|'center'; maxWidth?: number };
function text(doc: jsPDF, str: string, x: number, y: number, opts: TxtOpts = {}) {
  const { size = 9, bold = false, italic = false, color = INK, align = 'left', maxWidth } = opts;
  doc.setFont('helvetica', bold ? 'bold' : italic ? 'italic' : 'normal');
  doc.setFontSize(size);
  doc.setTextColor(color[0], color[1], color[2]);
  const s = str ?? '';
  if (maxWidth) {
    const lines = doc.splitTextToSize(s, maxWidth);
    doc.text(lines, x, y, { align, baseline: 'top' });
    return y + lines.length * (size * 0.42) + 1;
  }
  doc.text(s, x, y, { align, baseline: 'top' });
  return y + size * 0.42 + 1;
}
function line(doc: jsPDF, x1: number, y1: number, x2: number, y2: number, color: [number, number, number] = GRID, w = 0.2) {
  doc.setDrawColor(color[0], color[1], color[2]);
  doc.setLineWidth(w);
  doc.line(x1, y1, x2, y2);
}
function rect(doc: jsPDF, x: number, y: number, w: number, h: number, fill?: [number, number, number], stroke: [number, number, number] = GRID, sw = 0.2) {
  doc.setDrawColor(stroke[0], stroke[1], stroke[2]);
  doc.setLineWidth(sw);
  if (fill) {
    doc.setFillColor(fill[0], fill[1], fill[2]);
    doc.rect(x, y, w, h, 'FD');
  } else {
    doc.rect(x, y, w, h, 'S');
  }
}
function field(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value: string | number | undefined, opts: { labelSize?: number; valSize?: number; bold?: boolean; align?: 'left'|'center'|'right' } = {}) {
  rect(doc, x, y, w, h);
  doc.setFont('helvetica', 'bold').setFontSize(opts.labelSize ?? 6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(label.toUpperCase(), x + 1.5, y + 1.5, { baseline: 'top' });
  doc.setFont('helvetica', opts.bold ? 'bold' : 'normal').setFontSize(opts.valSize ?? 9).setTextColor(INK[0], INK[1], INK[2]);
  const v = value === undefined || value === null || value === '' ? '—' : String(value);
  const lines = doc.splitTextToSize(v, w - 3);
  doc.text(lines, x + 1.5, y + 4.8, { baseline: 'top', align: opts.align ?? 'left' });
}
function box(doc: jsPDF, x: number, y: number, w: number, h: number, title: string, body?: string) {
  rect(doc, x, y, w, h);
  doc.setFont('helvetica', 'bold').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(title.toUpperCase(), x + 1.5, y + 1.5, { baseline: 'top' });
  if (body) {
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
    const lines = doc.splitTextToSize(body, w - 3);
    doc.text(lines, x + 1.5, y + 5, { baseline: 'top' });
  }
}
function hline(doc: jsPDF, y: number) { line(doc, MARGIN_L, y, PAGE_W - MARGIN_R, y, GRID, 0.2); }
function fmtDate(d?: string) {
  if (!d) return '—';
  const dt = new Date(d);
  if (isNaN(dt.getTime())) return d;
  return dt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}
function fmtMoney(n: number, cur = 'USD') {
  try { return new Intl.NumberFormat('en-US', { style: 'currency', currency: cur, maximumFractionDigits: 2 }).format(n); } catch { return `${cur} ${n.toFixed(2)}`; }
}
function footer(doc: jsPDF, pageNum: number, total: number, color = BRAND) {
  const fy = 287;
  line(doc, MARGIN_L, fy - 2, PAGE_W - MARGIN_R, fy - 2, color, 0.3);
  doc.setFont('helvetica', 'italic').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('Generated by FreightFlow Logistics OS — computer-generated document.', MARGIN_L, fy, { baseline: 'top' });
  doc.text(`Page ${pageNum} / ${total}`, PAGE_W - MARGIN_R, fy, { align: 'right', baseline: 'top' });
}

// ============================================================
// AIR WAYBILL (IATA-style)
// ============================================================
export function generateShipmentBL(s: Shipment): Blob {
  const isAir = s.mode === 'air';
  if (!isAir) return generateFIATABL(s);   // delegate sea B/L to FIATA-style layout

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = 12;
  // --- Brand bar ---
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(0, 0, PAGE_W, 16, 'F');
  doc.setFont('helvetica', 'bold').setFontSize(16).setTextColor(255, 255, 255);
  doc.text('FREIGHTFLOW', MARGIN_L, 6, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(255, 255, 255);
  doc.text('Logistics OS · Antananarivo, Madagascar · ops@freightflow.mg', MARGIN_L, 12, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(10).setTextColor(255, 255, 255);
  doc.text('AIR WAYBILL — NON-NEGOTIABLE', PAGE_W - MARGIN_R, 7, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(8);
  doc.text(`Issued ${fmtDate(new Date().toISOString())}`, PAGE_W - MARGIN_R, 11.5, { align: 'right', baseline: 'top' });
  y = 20;

  // --- AWB number block ---
  const awbW = 70;
  const awbX = PAGE_W - MARGIN_R - awbW;
  rect(doc, MARGIN_L, y, 85, 22);
  doc.setFont('helvetica', 'bold').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('ISSUED BY', MARGIN_L + 2, y + 2, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(BRAND_DARK[0], BRAND_DARK[1], BRAND_DARK[2]);
  text(doc, 'FreightFlow Logistics SARL', MARGIN_L + 2, y + 6, { size: 11, bold: true, color: BRAND_DARK });
  doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(INK[0], INK[1], INK[2]);
  text(doc, 'Lot II M 86 Bis, Antananarivo 101', MARGIN_L + 2, y + 11, { size: 8 });
  text(doc, 'Madagascar · NIF 200 123 456', MARGIN_L + 2, y + 14.5, { size: 8 });
  text(doc, 'Tel: +261 20 22 123 45', MARGIN_L + 2, y + 17.5, { size: 8 });

  rect(doc, awbX, y, awbW, 22, BG_SOFT, BRAND, 0.6);
  doc.setFont('helvetica', 'bold').setFontSize(7).setTextColor(BRAND_DARK[0], BRAND_DARK[1], BRAND_DARK[2]);
  doc.text('AIR WAYBILL NUMBER', awbX + 2, y + 2, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(15).setTextColor(BRAND_DARK[0], BRAND_DARK[1], BRAND_DARK[2]);
  doc.text(String(s.mawbOrBl), awbX + 2, y + 7, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(`Shipper's Ref: ${s.reference}`, awbX + 2, y + 15, { baseline: 'top' });
  doc.text(`${s.direction.toUpperCase()} · ${s.incoterm}`, awbX + 2, y + 18, { baseline: 'top' });
  y += 26;

  // --- Shipper / Consignee / Agent grid ---
  const col3 = (CONTENT_W - 4) / 3;
  field(doc, MARGIN_L, y, col3, 22, "Shipper's Name & Address", `${s.customerName}\n${s.origin}`);
  field(doc, MARGIN_L + col3 + 2, y, col3, 22, 'Consignee\'s Name & Address', s.destination);
  field(doc, MARGIN_L + 2 * (col3 + 2), y, col3, 22, 'Issuing Carrier\'s Agent', 'FreightFlow Logistics\nAntananarivo (TNR), MG');
  y += 26;

  // --- Routing (box 2-rows) ---
  const routingH = 18;
  field(doc, MARGIN_L, y, col3, routingH, 'Airport of Departure (Addr. of first Carrier) & requested Routing', s.portOfLoading);
  field(doc, MARGIN_L + col3 + 2, y, col3 * 0.5, routingH, 'To (1st)', s.portOfDischarge);
  field(doc, MARGIN_L + col3 + 2 + col3 * 0.5 + 2, y, col3 * 0.5 - 2, routingH, 'By First Carrier', s.carrier);
  field(doc, MARGIN_L + 2 * (col3 + 2), y, col3, routingH, 'Airport of Destination', s.portOfDischarge);
  y += routingH + 2;

  // --- Flight/date, terms, weight ---
  const wh = 18;
  field(doc, MARGIN_L, y, 50, wh, 'Flight / Date', `${s.vesselOrFlight || '—'}\nETD ${fmtDate(s.etd)}`);
  field(doc, MARGIN_L + 52, y, 30, wh, 'Currency', s.currency);
  field(doc, MARGIN_L + 84, y, 25, wh, 'CHGS Code', 'PPD');
  field(doc, MARGIN_L + 111, y, 35, wh, 'WT/VAL', 'PREPAID');
  field(doc, MARGIN_L + 148, y, 38, wh, 'Other', 'PREPAID');
  y += wh + 2;

  // --- Cargo table ---
  const tblTop = y;
  rect(doc, MARGIN_L, y, CONTENT_W, 7, BG_SOFT);
  doc.setFont('helvetica', 'bold').setFontSize(7).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('PIECES', MARGIN_L + 2, y + 2, { baseline: 'top' });
  doc.text('GROSS WEIGHT (kg)', MARGIN_L + 25, y + 2, { baseline: 'top' });
  doc.text('KG/LB', MARGIN_L + 58, y + 2, { baseline: 'top' });
  doc.text('RATE CLASS', MARGIN_L + 68, y + 2, { baseline: 'top' });
  doc.text('CHARGEABLE WEIGHT (kg)', MARGIN_L + 82, y + 2, { baseline: 'top' });
  doc.text('RATE/kg', MARGIN_L + 125, y + 2, { baseline: 'top' });
  doc.text('NATURE & QUANTITY OF GOODS', MARGIN_L + 140, y + 2, { baseline: 'top' });
  y += 7;
  const chg = s.chargeableWeight ?? Math.max(s.weight, (s.volume * 1e6) / 6000);
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
  doc.text(String(s.pieces), MARGIN_L + 2, y + 3, { baseline: 'top' });
  doc.text(fmtNum(s.weight, 1), MARGIN_L + 25, y + 3, { baseline: 'top' });
  doc.text('K', MARGIN_L + 58, y + 3, { baseline: 'top' });
  doc.text('Q', MARGIN_L + 68, y + 3, { baseline: 'top' });
  doc.text(fmtNum(chg, 1), MARGIN_L + 82, y + 3, { baseline: 'top' });
  const ratePerKg = chg > 0 ? s.totalAmount / chg : 0;
  doc.text(ratePerKg.toFixed(2), MARGIN_L + 125, y + 3, { baseline: 'top' });
  const commLines = doc.splitTextToSize(s.commodity, CONTENT_W - 142);
  doc.text(commLines, MARGIN_L + 140, y + 3, { baseline: 'top' });
  const rowH = Math.max(12, commLines.length * 4.2 + 4);
  rect(doc, MARGIN_L, tblTop, CONTENT_W, 7 + rowH);
  // vertical separators
  [24, 38, 55, 78, 122, 138].forEach(xx => line(doc, MARGIN_L + xx, tblTop, MARGIN_L + xx, tblTop + 7 + rowH));
  y += rowH + 2;

  // --- Prepaid totals ---
  field(doc, MARGIN_L, y, CONTENT_W * 0.5, 14, 'Weight Charge (Prepaid)', fmtMoney(s.totalAmount * 0.85, s.currency));
  field(doc, MARGIN_L + CONTENT_W * 0.5 + 2, y, CONTENT_W * 0.5 - 2, 14, 'Other Charges', fmtMoney(s.totalAmount * 0.15, s.currency));
  y += 16;
  field(doc, MARGIN_L, y, CONTENT_W * 0.5, 14, 'Total Prepaid', fmtMoney(s.totalAmount, s.currency), { bold: true });
  field(doc, MARGIN_L + CONTENT_W * 0.5 + 2, y, CONTENT_W * 0.5 - 2, 14, 'Declared Value for Carriage', fmtMoney(s.totalAmount * 1.1, s.currency));
  y += 16;

  // --- Handling info ---
  box(doc, MARGIN_L, y, CONTENT_W, 28, 'Handling Information',
    `${s.notes || '—'}\n\nChargeable weight computed per IATA 1:6000 volumetric formula. Dimensions: per shipper\'s declaration. Dangerous Goods: NOT RESTRICTED.`);
  y += 30;

  // --- Signatures ---
  const sigH = 16;
  box(doc, MARGIN_L, y, CONTENT_W * 0.48, sigH, "Shipper's Certification", `By: ${s.customerName}\nDate: ${fmtDate(new Date().toISOString())}`);
  box(doc, MARGIN_L + CONTENT_W * 0.52, y, CONTENT_W * 0.48, sigH, "Carrier's Execution", `FreightFlow as agent for ${s.carrier}\nPlace: Antananarivo, ${fmtDate(new Date().toISOString())}`);

  footer(doc, 1, 1);
  return doc.output('blob');
}

// ============================================================
// FIATA MULTIMODAL TRANSPORT BILL OF LADING (FBL)
// Official FIATA-style B/L — used for FCL/LCL sea freight.
// Layout modelled on the FIATA FBL (ICC-UNCTAD) form:
//   - Yellow/blue FIATA identity block top-left
//   - Shipper / Consignee / Notify in numbered boxes (1,2,3)
//   - Place/port of receipt (4), Vessel (5), Port of loading (6),
//     Port of discharge (7), Place of delivery (8)
//   - Marks & Nos (9), Number/kind of pkgs (10), Description (11),
//     Gross weight (12), Measurement (13)
//   - Freight & charges (14), Number of originals (15), Place/date (16),
//     Signature (17)
// ============================================================
function generateFIATABL(s: Shipment): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const BLUE = [25, 65, 120] as [number, number, number];
  const GOLD = [190, 150, 60] as [number, number, number];
  const W = CONTENT_W;
  let y = 10;

  // ===== HEADER =====
  // FIATA-style header band
  doc.setFillColor(BLUE[0], BLUE[1], BLUE[2]);
  doc.rect(0, 0, PAGE_W, 24, 'F');
  // gold accent
  doc.setFillColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.rect(0, 24, PAGE_W, 1.5, 'F');

  doc.setFont('helvetica', 'bold').setFontSize(18).setTextColor(255, 255, 255);
  doc.text('FIATA', MARGIN_L, 5, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(220, 230, 245);
  doc.text('Fédération Internationale des Associations de Transitaires et Assimilés', MARGIN_L, 12, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(255, 255, 255);
  doc.text('MULTIMODAL TRANSPORT BILL OF LADING', MARGIN_L, 16, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(7).setTextColor(220, 230, 245);
  doc.text('Negotiable · Subject to UNCTAD/ICC Rules for Multimodal Transport Documents (ICC Publication 481)', MARGIN_L, 20, { baseline: 'top' });

  // Negotiable/Non-negotiable mark on right
  doc.setFont('helvetica', 'bold').setFontSize(14).setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.text('NEGOTIABLE', PAGE_W - MARGIN_R, 5, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(7).setTextColor(220, 230, 245);
  doc.text(`B/L No. ${s.mawbOrBl}`, PAGE_W - MARGIN_R, 11, { align: 'right', baseline: 'top' });
  doc.text(`Shipper's Ref: ${s.reference}`, PAGE_W - MARGIN_R, 14.5, { align: 'right', baseline: 'top' });
  doc.text(`Carrier's Ref: FLOW-${s.reference.slice(-6)}`, PAGE_W - MARGIN_R, 17.5, { align: 'right', baseline: 'top' });
  y = 30;

  // ===== 1 Shipper, 2 Consignee, 3 Notify =====
  const third = (W - 2) / 3;
  field(doc, MARGIN_L, y, third, 24, '1. Shipper (full name, address, country)',
    `${s.customerName}\n${s.origin}`);
  field(doc, MARGIN_L + third + 1, y, third, 24, '2. Consignee (full name, address, country) — TO ORDER',
    `${s.customerName} or order\n${s.destination}`);
  field(doc, MARGIN_L + 2 * (third + 1), y, third, 24, '3. Notify Party (full name, address, country)',
    s.destination);
  y += 26;

  // ===== 4 Place of receipt, 5 Vessel, 6 Port of loading =====
  const h2 = 16;
  field(doc, MARGIN_L, y, third, h2, '4. Place of Receipt (applicable when pre-carriage performed)', s.origin);
  field(doc, MARGIN_L + third + 1, y, third, h2, '5. Ocean Vessel / Voyage No.', s.vesselOrFlight || 'TBD');
  field(doc, MARGIN_L + 2 * (third + 1), y, third, h2, '6. Port of Loading', s.portOfLoading);
  y += h2 + 2;

  // ===== 7 Port of discharge, 8 Place of delivery, Freight payable =====
  field(doc, MARGIN_L, y, third, h2, '7. Port of Discharge', s.portOfDischarge);
  field(doc, MARGIN_L + third + 1, y, third, h2, '8. Place of Delivery', s.destination);
  field(doc, MARGIN_L + 2 * (third + 1), y, third, h2, 'Freight Payable at', 'Antananarivo, MG');
  y += h2 + 2;

  // ===== Cargo table (boxes 9-13) =====
  const tblY = y;
  const colX = [
    MARGIN_L,                               // 9 Marks left
    MARGIN_L + 30,                          // 10 Nos & pkgs
    MARGIN_L + 50,                          // 11 Description
    MARGIN_L + W - 52,                      // 12 Gross weight
    MARGIN_L + W - 25,                      // 13 Measurement
  ];
  // header
  doc.setFillColor(BG_SOFT[0], BG_SOFT[1], BG_SOFT[2]);
  doc.rect(MARGIN_L, y, W, 8, 'FD');
  doc.setDrawColor(GRID[0], GRID[1], GRID[2]).setLineWidth(0.2);
  for (let i = 0; i < colX.length - 1; i++) doc.line(colX[i + 1], y, colX[i + 1], y + 8);
  doc.setFont('helvetica', 'bold').setFontSize(6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('9. MARKS & NOS', colX[0] + 1.5, y + 1.5, { baseline: 'top' });
  doc.text('10. NOS & KIND\nOF PKGS', colX[1] + 1.5, y + 1.2, { baseline: 'top' });
  doc.text('11. DESCRIPTION OF GOODS', colX[2] + 1.5, y + 1.5, { baseline: 'top' });
  doc.text('12. GROSS WEIGHT\n(kg)', colX[3] + 1.5, y + 1.2, { baseline: 'top' });
  doc.text('13. MEASUREMENT\n(CBM)', colX[4] + 1.5, y + 1.2, { baseline: 'top' });
  y += 8;

  const body = s.commodity + (s.notes ? `\n${s.notes}` : '');
  const bodyLines = doc.splitTextToSize(body, colX[3] - colX[2] - 3);
  const marks = (s.mawbOrBl + '\nC/NO. 1-' + s.pieces + '\nMADE IN MG').toUpperCase();
  const marksLines = doc.splitTextToSize(marks, colX[1] - colX[0] - 3);
  const pkgsStr = `${s.pieces} ${s.pieces === 1 ? 'PACKAGE' : 'PACKAGES'}\n${s.volume >= 14 ? '1×20GP' : s.volume >= 28 ? '1×40GP' : 'LCL'}`;
  const rowH = Math.max(24, Math.max(bodyLines.length, marksLines.length) * 3.8 + 6);

  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
  doc.text(marksLines, colX[0] + 1.5, y + 2, { baseline: 'top' });
  doc.setFont('helvetica', 'bold');
  doc.text(pkgsStr, colX[1] + 1.5, y + 2, { baseline: 'top' });
  doc.setFont('helvetica', 'normal');
  doc.text(bodyLines, colX[2] + 1.5, y + 2, { baseline: 'top' });
  doc.text(`${fmtNum(s.weight, 1)} kg`, colX[3] + 1.5, y + 2, { baseline: 'top' });
  doc.text(`${fmtNum(s.volume, 3)} m³`, colX[4] + 1.5, y + 2, { baseline: 'top' });

  // outer box + vertical separators for table
  rect(doc, MARGIN_L, tblY, W, 8 + rowH);
  for (let i = 1; i < colX.length; i++) line(doc, colX[i], tblY, colX[i], tblY + 8 + rowH);
  y += 8 + rowH + 2;

  // ===== 14 Freight & charges =====
  const cH = 28;
  const cW = (W - 2) / 2;
  field(doc, MARGIN_L, y, cW, cH, '14. FREIGHT & CHARGES (prepaid as per booking)',
    `Ocean Freight:  ${fmtMoney(s.totalAmount * 0.75, s.currency)}\nTHC/DOC:        ${fmtMoney(s.totalAmount * 0.10, s.currency)}\nInland trucking: ${fmtMoney(s.truckingCost ?? s.totalAmount * 0.15, s.currency)}\n${s.incoterm} — ${s.direction.toUpperCase()}`);
  field(doc, MARGIN_L + cW + 2, y, cW, cH, 'PARTICULARS DECLARED BY SHIPPER',
    `Total pieces:  ${s.pieces}\nTotal weight:  ${fmtNum(s.weight, 1)} kg\nTotal volume:  ${fmtNum(s.volume, 3)} m³\nDeclared value: ${fmtMoney(s.totalAmount, s.currency)}`);
  y += cH + 2;

  // ===== TOTAL BOXES + DATE / SIGN =====
  const sigH = 30;
  field(doc, MARGIN_L, y, W * 0.3, sigH, '15. NUMBER OF ORIGINAL Bs/L',
    `THREE (3/3) issued,\none being accomplished,\nthe others to stand void.`);
  field(doc, MARGIN_L + W * 0.3 + 2, y, W * 0.32 - 2, sigH, '16. PLACE AND DATE OF ISSUE',
    `Antananarivo, Madagascar\n${fmtDate(new Date().toISOString())}\nETD: ${fmtDate(s.etd)}  ·  ETA: ${fmtDate(s.eta)}`);
  field(doc, MARGIN_L + W * 0.62, y, W * 0.38, sigH, '17. SIGNED FOR THE CARRIER',
    `FreightFlow Logistics SARL\nas Multimodal Transport Operator (MTO)\n\n________________________________\nAuthorized Signatory · ${s.carrier} agent`);
  y += sigH + 4;

  // ===== REVERSE TERMS (short clause block) =====
  rect(doc, MARGIN_L, y, W, 28, [250, 250, 252], GRID);
  doc.setFont('helvetica', 'bold').setFontSize(6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('TERMS AND CONDITIONS ON REVERSE (abridged)', MARGIN_L + 2, y + 2, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(6.5).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  const terms = 'This Bill of Lading, issued in the FIATA FBL format, is subject to the UNCTAD/ICC Rules for Multimodal Transport Documents (ICC Pub. 481). The Merchant agrees that the MTO\'s liability shall be as set out in those Rules and, where compulsorily applicable, the Hague-Visby Rules. Freight is deemed earned upon receipt of cargo and is non-returnable. The goods have been received in apparent good order and condition unless noted hereon. The Carrier/MTO shall not be liable for indirect or consequential loss.';
  const tl = doc.splitTextToSize(terms, W - 4);
  doc.text(tl, MARGIN_L + 2, y + 6, { baseline: 'top' });

  footer(doc, 1, 1, BLUE);
  return doc.output('blob');
}

// ============================================================
// COMMERCIAL INVOICE — clean, professional
// ============================================================
export function generateInvoicePDF(inv: Invoice): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = 12;
  // brand header
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(0, 0, PAGE_W, 18, 'F');
  doc.setFont('helvetica', 'bold').setFontSize(18).setTextColor(255, 255, 255);
  doc.text('FREIGHTFLOW', MARGIN_L, 6, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(255, 255, 255);
  doc.text('FreightFlow Logistics SARL · Antananarivo, Madagascar · ops@freightflow.mg', MARGIN_L, 12.5, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(16).setTextColor(255, 255, 255);
  doc.text('INVOICE', PAGE_W - MARGIN_R, 5, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(9);
  doc.text(`No. ${inv.number}`, PAGE_W - MARGIN_R, 11, { align: 'right', baseline: 'top' });
  y = 24;

  // Bill-to / invoice meta boxes
  const bw = (W - 4) / 3;
  field(doc, MARGIN_L, y, bw, 24, 'BILL TO', inv.customerName);
  field(doc, MARGIN_L + bw + 2, y, bw, 24, 'INVOICE DETAILS',
    `Issue date: ${fmtDate(inv.issueDate)}\nDue date:   ${fmtDate(inv.dueDate)}\nStatus:     ${inv.status.toUpperCase()}\nCurrency:   ${inv.currency}`);
  field(doc, MARGIN_L + 2 * (bw + 2), y, bw, 24, 'PAYMENT',
    `Bank: BNI Madagascar\nSWIFT: BNIMMGAA\nIBAN: MG46 0000 5000 0100 1234 5678 90\nTerms: Net ${Math.max(0, Math.ceil((new Date(inv.dueDate).getTime() - new Date(inv.issueDate).getTime()) / 86400000))} days`);
  y += 28;

  // Items table
  const tblTop = y;
  const colW = [85, 28, 25, 28];  // desc, qty, rate, amount
  const colStarts = [MARGIN_L, MARGIN_L + colW[0], MARGIN_L + colW[0] + colW[1], MARGIN_L + colW[0] + colW[1] + colW[2]];
  rect(doc, MARGIN_L, y, W, 7, BG_SOFT);
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('DESCRIPTION', colStarts[0] + 2, y + 2, { baseline: 'top' });
  doc.text('QTY', colStarts[1] + colW[1] - 2, y + 2, { align: 'right', baseline: 'top' });
  doc.text('RATE', colStarts[2] + colW[2] - 2, y + 2, { align: 'right', baseline: 'top' });
  doc.text('AMOUNT', colStarts[3] + colW[3] - 2, y + 2, { align: 'right', baseline: 'top' });
  y += 7;

  let subtotal = 0;
  inv.items.forEach((it, idx) => {
    const isLast = idx === inv.items.length - 1;
    const lines = doc.splitTextToSize(it.description, colW[0] - 4);
    const rh = Math.max(7, lines.length * 4 + 2);
    if (idx % 2 === 1) doc.setFillColor(250, 251, 253).rect(MARGIN_L, y, W, rh, 'F');
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
    doc.text(lines, colStarts[0] + 2, y + 1.5, { baseline: 'top' });
    doc.text('1', colStarts[1] + colW[1] - 2, y + 2, { align: 'right', baseline: 'top' });
    doc.text(fmtMoney(it.amount, inv.currency), colStarts[2] + colW[2] - 2, y + 2, { align: 'right', baseline: 'top' });
    doc.text(fmtMoney(it.amount, inv.currency), colStarts[3] + colW[3] - 2, y + 2, { align: 'right', baseline: 'top' });
    subtotal += it.amount;
    y += rh;
    if (!isLast) line(doc, MARGIN_L, y, MARGIN_L + W, y, GRID, 0.15);
  });
  rect(doc, MARGIN_L, tblTop, W, y - tblTop);  // outer border
  for (let i = 1; i < colStarts.length; i++) line(doc, colStarts[i], tblTop, colStarts[i], y);
  y += 2;

  // totals (right aligned)
  const totX = MARGIN_L + W - 60;
  const totW = 60;
  const tot = (label: string, value: string, bold = false, fill = false) => {
    const h = 7;
    if (fill) { doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]); doc.rect(totX, y, totW, h, 'F'); }
    doc.setFont('helvetica', bold ? 'bold' : 'normal').setFontSize(bold ? 11 : 9).setTextColor(fill ? 255 : INK[0], fill ? 255 : INK[1], fill ? 255 : INK[2]);
    doc.text(label, totX + 3, y + 2, { baseline: 'top' });
    doc.text(value, totX + totW - 3, y + 2, { align: 'right', baseline: 'top' });
    y += h;
  };
  tot('Subtotal', fmtMoney(inv.subtotal, inv.currency));
  tot('VAT / Tax (0%)', fmtMoney(inv.tax, inv.currency));
  tot('TOTAL DUE', fmtMoney(inv.total, inv.currency), true, true);
  y += 4;

  // Status stamp / paid
  if (inv.status === 'paid') {
    doc.setDrawColor(20, 140, 70).setLineWidth(0.8).setTextColor(20, 140, 70);
    doc.setFont('helvetica', 'bold').setFontSize(14);
    doc.roundedRect(totX, y + 2, totW, 10, 2, 2, 'S');
    doc.text('PAID', totX + totW / 2, y + 5, { align: 'center', baseline: 'top' });
    doc.setTextColor(INK[0], INK[1], INK[2]);
    y += 14;
  } else if (inv.status === 'overdue') {
    doc.setDrawColor(180, 40, 40).setLineWidth(0.8).setTextColor(180, 40, 40);
    doc.setFont('helvetica', 'bold').setFontSize(14);
    doc.roundedRect(totX, y + 2, totW, 10, 2, 2, 'S');
    doc.text('OVERDUE', totX + totW / 2, y + 5, { align: 'center', baseline: 'top' });
    doc.setTextColor(INK[0], INK[1], INK[2]);
    y += 14;
  } else {
    y += 4;
  }

  // OOBO / e-invoice block
  if (inv.einvoice) {
    rect(doc, MARGIN_L, y, W, 16, [235, 250, 240], [80, 160, 110], 0.5);
    doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(20, 90, 50);
    doc.text('OOBO / DGI E-INVOICE (MADAGASCAR)', MARGIN_L + 3, y + 2, { baseline: 'top' });
    doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(20, 90, 50);
    doc.text(`UID: ${inv.einvoice.ooboUid ?? 'pending'}  ·  NIF Emitter: ${inv.einvoice.nifEmitter}  ·  HTVA: ${fmtMoney(inv.einvoice.htva, inv.currency)}  ·  VAT (${(inv.einvoice.tvaRate * 100).toFixed(0)}%): ${fmtMoney(inv.einvoice.tva, inv.currency)}  ·  TTC: ${fmtMoney(inv.einvoice.ttc, inv.currency)}  ·  Payment: ${inv.einvoice.paymentMethod.toUpperCase()}`, MARGIN_L + 3, y + 8, { baseline: 'top' });
    y += 18;
  }

  // thank-you
  doc.setFont('helvetica', 'italic').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('Thank you for your business. 🇲🇬 Payment is due per agreed terms; bank details above.', MARGIN_L, y + 4, { baseline: 'top' });

  footer(doc, 1, 1);
  return doc.output('blob');
}

// ============================================================
// QUOTATION
// ============================================================
export function generateQuotePDF(q: Quote): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = 12;
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(0, 0, PAGE_W, 18, 'F');
  doc.setFont('helvetica', 'bold').setFontSize(18).setTextColor(255, 255, 255);
  doc.text('FREIGHTFLOW', MARGIN_L, 6, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(255, 255, 255);
  doc.text('FreightFlow Logistics SARL · Antananarivo, Madagascar · quotes@freightflow.mg', MARGIN_L, 12.5, { baseline: 'top' });
  doc.setFont('helvetica', 'bold').setFontSize(16).setTextColor(255, 255, 255);
  doc.text('FREIGHT QUOTATION', PAGE_W - MARGIN_R, 5, { align: 'right', baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(9);
  doc.text(`No. ${q.number}`, PAGE_W - MARGIN_R, 11, { align: 'right', baseline: 'top' });
  doc.text(`Valid until: ${fmtDate(q.validUntil)}`, PAGE_W - MARGIN_R, 14, { align: 'right', baseline: 'top' });
  y = 24;

  // Customer & routing block
  const bw = (W - 2) / 2;
  field(doc, MARGIN_L, y, bw, 22, 'PREPARED FOR',
    `${q.customerName}\n${q.customerEmail ?? ''}`);
  field(doc, MARGIN_L + bw + 2, y, bw, 22, 'ROUTING',
    `${q.mode.toUpperCase()} ${q.direction.toUpperCase()}\n${q.origin}  →  ${q.destination}\nCommodity: ${q.commodity} · ${fmtNum(q.weight, 1)} kg · ${fmtNum(q.volume, 3)} CBM`);
  y += 26;

  // Items
  rect(doc, MARGIN_L, y, W, 7, BG_SOFT);
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('CHARGE ITEM', MARGIN_L + 3, y + 2, { baseline: 'top' });
  doc.text('AMOUNT (USD)', MARGIN_L + W - 3, y + 2, { align: 'right', baseline: 'top' });
  y += 7;
  const items: [string, number][] = [
    ['Freight charges (ocean/air)', q.freightRate],
    ['Customs processing & documentation', q.customsFee],
    ['Inland trucking & delivery', q.truckingFee],
  ];
  items.forEach(([lbl, amt], i) => {
    const rh = 7;
    if (i % 2 === 1) doc.setFillColor(250, 251, 253).rect(MARGIN_L, y, W, rh, 'F');
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(INK[0], INK[1], INK[2]);
    doc.text(lbl, MARGIN_L + 3, y + 2, { baseline: 'top' });
    doc.text(fmtMoney(amt, 'USD'), MARGIN_L + W - 3, y + 2, { align: 'right', baseline: 'top' });
    y += rh;
  });
  line(doc, MARGIN_L, y, MARGIN_L + W, y);
  y += 1;
  doc.setFont('helvetica', 'bold').setFontSize(12).setTextColor(BRAND_DARK[0], BRAND_DARK[1], BRAND_DARK[2]);
  doc.text('ALL-IN TOTAL', MARGIN_L + 3, y + 2, { baseline: 'top' });
  doc.text(fmtMoney(q.total, 'USD'), MARGIN_L + W - 3, y + 2, { align: 'right', baseline: 'top' });
  y += 10;

  // T&Cs
  rect(doc, MARGIN_L, y, W, 42, [250, 250, 252], GRID);
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text('TERMS & CONDITIONS', MARGIN_L + 3, y + 2, { baseline: 'top' });
  doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  const tc = [
    '• Rates valid until date shown above, subject to carrier space, equipment availability and bunker/security surcharges.',
    '• Quoted amounts exclude insurance, duties, taxes (VAT/TVA), demurrage, detention and storage beyond free time (7 days at CFS).',
    '• Transit times are estimates; FreightFlow is not liable for carrier schedule changes, customs inspection delays or force majeure.',
    '• Dangerous goods / perishables require prior written approval and may incur additional handling fees.',
    '• Payment terms: 50% deposit on booking confirmation; balance due prior to document / cargo release.',
    '• Quotation may be accepted by signed return, email confirmation or by tendering cargo against this reference.',
  ].join('\n');
  doc.text(doc.splitTextToSize(tc, W - 6), MARGIN_L + 3, y + 6, { baseline: 'top' });

  footer(doc, 1, 1);
  return doc.output('blob');
}

// ============================================================
// Download helper
// ============================================================
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// format number helper for docs
function fmtNum(n: number, d: number) {
  return new Intl.NumberFormat('en-US', { minimumFractionDigits: n % 1 ? d : 0, maximumFractionDigits: d }).format(n);
}
